# Generated by Django 4.0 on 2021-12-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='last_benchmarked',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
