# Generated by Django 4.0 on 2021-12-29 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('sites', '0002_site_last_benchmarked'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='siteaccess',
            unique_together={('site', 'user')},
        ),
        migrations.CreateModel(
            name='VerificationCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
