# Generated by Django 4.0 on 2022-01-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_free_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
