# Generated by Django 4.0 on 2022-01-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_alter_package_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='stripe_price_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='package',
            name='stripe_product_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
