# Generated by Django 4.0 on 2022-01-13 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_intent_id', models.CharField(max_length=255, unique=True)),
                ('object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_type', models.CharField(max_length=20)),
                ('last_4_digits', models.CharField(max_length=4)),
                ('exp_month', models.PositiveIntegerField(verbose_name='Expiry month')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Payment History',
                'verbose_name_plural': 'Payment History',
                'ordering': ['-created_on'],
            },
        ),
    ]
