export const SHOW_OVERLAY = "SHOW_OVERLAY";
export const HIDE_OVERLAY = "HIDE_OVERLAY";
export const SHOW_SIGN_UP_PAGE = "SHOW_SIGN_UP_PAGE";
export const SHOW_LOGIN_PAGE = "SHOW_LOGIN_PAGE";
export const UPDATE_ERROR_MESSAGE = "UPDATE_ERROR_MESSAGE";
