# Generated by Django 4.0 on 2022-01-11 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_packagehistory_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packagehistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_history', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='packagehistory',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
