# Generated by Django 4.0 on 2022-01-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_packagehistory_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagehistory',
            name='paid_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
